name: Dempployment CD

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - "main"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: coffee-build
          path: |
            ./dist
            ./public
            
  staging-deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging Environment..."

  integration-tests-staging:
    runs-on: self-hosted
    needs: staging-deploy
    steps:
      - name: Run Integration Tests on Staging
        run: echo "Running Integration Tests on Staging..."

  production-deploy:
    runs-on: self-hosted
    needs: integration-tests-staging
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production Environment..."

  integration-tests-production:
    runs-on: self-hosted
    needs: production-deploy
    steps:
      - name: Run Integration Tests on Production
        run: echo "Running Integration Tests on Production..."
