name: Pull Request CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Linter
        run: echo "Configuring Linter..."

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Set up Testing Environment
        run: echo "Setting up Testing Environment..."

  build:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Build Project
        run: echo "Building Project..."
