name: Deployment CD

on:
  push:
    branches:
      - "release/*"

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  unit-tests:
    runs-on: self-hosted
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run unit-test

  audit:
    runs-on: self-hosted
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=high
  build:
    runs-on: self-hosted
    needs: audit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: coffee-build
          path: |
            ./dist
            ./public
            ./package-lock.json
            ./package.json

  staging-deploy:
    needs: build
    uses: yaswanth67/infra-deployment/.github/workflows/staging_deployment_coffee.yml@main
    with:
      build_id: ${{ github.run_id }}
    secrets: inherit

  integration-tests-staging:
    runs-on: self-hosted
    needs: staging-deploy
    env:
      STAGING_BASE_URL: "http://${{ secrets.STAGING_IP }}/coffee-app"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Smoke-staging tests
        run: npm run smoke-staging

  production-deploy:
    needs: integration-tests-staging
    uses: yaswanth67/infra-deployment/.github/workflows/production_deployment_coffee.yml@main
    with:
      build_id: ${{ github.run_id }}
    secrets: inherit

  integration-tests-production:
    runs-on: self-hosted
    needs: production-deploy
    env:
      PROD_BASE_URL: "http://${{ secrets.PRODUCTION_IP }}/coffee-app"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Smoke-prod tests
        run: npm run smoke-prod
